name: Test
on: 
  push:
    branches:
    - master
jobs:
  testRunPython:
    name: Test python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - run: python test.py
